### ISSUE TITLE
Question about the addError method

### ISSUE THREAD

**Issue by angelvilaplana** [owebia/magento2-module-advanced-shipping#99]
Hello everybody!

I'm testing this nice module and I've a question about the addError method.
By any chance, can you get this error value in Magento frontend?

Thank you very much and have a nice day!!

**Comment by owebia** [comment]
Hi,

Yes, this is the purpose of  `addError`, it should be displayed on the area displaying the shipping methods.

Best Regards,
A.L.

**Comment by angelvilaplana** [comment]
Hi,

Thany you so much for your answer. I've tried it and I get the default message "Sorry, no quotes are available for this order at this time".

This is my testing code:
```php
addMethod('id_1', [
    'title'      => "Shipping France",
    'enabled'    => $request->dest_country_id == 'FR',
    'price'      => 10,
]);


if (count(getMethods(true)) == 0) {
    addError('No shipping method available');
}
```


For the rest, everything works well.
Thank you very much!!

**Comment by owebia** [comment]
It seems Magento now requires at least one shipping method displayed for the carrier, to display an error on the frontend (because the error is associated to a carrier).

You can activate the option "Show Method if Not Applicable" but I'm not sure that's what you want to do.

The last remaining option is to override the default behavior of Magento.

Best Regards,
A.L.

**Comment by angelvilaplana** [comment]
Hi again,

Thank you again for your answer. I've done the activate the option and the error is displayed. 
I think it doesn't work because it didn't enter the loop of the shipping methods in the "cart/shipping-rates.html", and there are a line in the code "<div data-bind="text: error_message"></div>" which is where it shows the error.

Thanks so much for the help!! :)
